<script lang="ts" setup>
const { t } = useI18n();
const localePath = useLocalePath();

useSeoMeta({
  title: computed(() => t("servicesPage.seo.title")),
  description: computed(() => t("servicesPage.seo.description")),
  keywords: computed(() => t("servicesPage.seo.keywords")),
});

// Dynamic OG Image generated by nuxt-og-image
defineOgImage("Controlla.takumi", {
  title: computed(() => t("servicesPage.seo.title")),
  description: computed(() => t("servicesPage.seo.description")),
});

// Automated Schema.org by nuxt-schema-org
useSchemaOrg([
  defineWebPage({
    name: computed(() => t("servicesPage.seo.title")),
    description: computed(() => t("servicesPage.seo.description")),
  })
]);
</script>

<template>
  <main class="flex flex-col flex-1 pt-32 pb-24">
    <!-- Hero Section -->
    <section
      class="max-w-4xl mx-auto px-6 lg:px-8 mb-20 text-center relative z-10"
    >
      <div
        class="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-surface-100 dark:bg-surface-800 border border-surface-200 dark:border-surface-700 mb-8"
      >
        <span class="w-2 h-2 rounded-full bg-primary-500 animate-pulse"></span>
        <span
          class="font-mono text-[11px] font-semibold text-surface-600 dark:text-surface-300 tracking-widest uppercase"
        >
          {{ $t("servicesPage.badge") }}
        </span>
      </div>
      <h1
        class="text-5xl md:text-6xl font-bold text-surface-900 dark:text-surface-0 mb-6 tracking-tight leading-tight"
      >
        {{ $t("servicesPage.heroTitle") }}
      </h1>
      <p
        class="text-lg text-surface-600 dark:text-surface-300 max-w-2xl mx-auto leading-relaxed"
      >
        {{ $t("servicesPage.heroSubtitle") }}
      </p>
    </section>

    <!-- Services Bento Grid -->
    <section class="max-w-7xl mx-auto px-6 lg:px-8 mb-32 relative z-10">
      <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
        <!-- Card 1: Software Engineering (Span 2) -->
        <article
          class="md:col-span-2 bg-surface-0 dark:bg-surface-900 rounded-2xl border border-surface-200 dark:border-surface-800 p-8 hover:border-surface-300 dark:hover:border-surface-700 hover:shadow-xl dark:shadow-none transition-all duration-300 flex flex-col group"
        >
          <div
            class="mb-6 inline-flex items-center justify-center w-12 h-12 rounded-lg border border-surface-100 dark:border-surface-800 bg-surface-50 dark:bg-surface-950 text-surface-700 dark:text-surface-300 group-hover:border-primary-500/20 group-hover:bg-primary-500/10 group-hover:text-primary-500 transition-colors"
          >
            <i class="pi pi-code text-xl"></i>
          </div>
          <h3
            class="text-2xl font-bold text-surface-900 dark:text-surface-0 mb-3 tracking-tight"
          >
            {{ $t("servicesPage.cards.software.title") }}
          </h3>
          <p
            class="text-surface-600 dark:text-surface-400 mb-8 max-w-xl leading-relaxed"
          >
            {{ $t("servicesPage.cards.software.desc") }}
          </p>
          <ul class="space-y-3 mb-8">
            <li class="flex items-center gap-3">
              <i class="pi pi-check-circle text-primary-500"></i>
              <span
                class="font-mono text-sm text-surface-700 dark:text-surface-300"
                >{{ $t("servicesPage.cards.software.feat1") }}</span
              >
            </li>
            <li class="flex items-center gap-3">
              <i class="pi pi-check-circle text-primary-500"></i>
              <span
                class="font-mono text-sm text-surface-700 dark:text-surface-300"
                >{{ $t("servicesPage.cards.software.feat2") }}</span
              >
            </li>
          </ul>
          <div class="mt-auto pt-6">
            <NuxtLink
              :to="localePath('/contact')"
              class="inline-flex items-center gap-2 font-semibold text-sm text-surface-900 dark:text-surface-0 hover:text-primary-500 dark:hover:text-primary-400 transition-colors w-fit group/link"
            >
              {{ $t("servicesPage.cards.software.link") }}
              <i
                class="pi pi-arrow-right text-xs group-hover/link:translate-x-1 transition-transform"
              ></i>
            </NuxtLink>
          </div>
        </article>

        <!-- Card 2: Nearshore (Span 1) -->
        <article
          class="md:col-span-1 bg-surface-0 dark:bg-surface-900 rounded-2xl border border-surface-200 dark:border-surface-800 p-8 hover:border-surface-300 dark:hover:border-surface-700 hover:shadow-xl dark:shadow-none transition-all duration-300 flex flex-col group"
        >
          <div
            class="mb-6 inline-flex items-center justify-center w-12 h-12 rounded-lg border border-surface-100 dark:border-surface-800 bg-surface-50 dark:bg-surface-950 text-surface-700 dark:text-surface-300 group-hover:border-primary-500/20 group-hover:bg-primary-500/10 group-hover:text-primary-500 transition-colors"
          >
            <i class="pi pi-globe text-xl"></i>
          </div>
          <h3
            class="text-2xl font-bold text-surface-900 dark:text-surface-0 mb-3 tracking-tight"
          >
            {{ $t("servicesPage.cards.nearshore.title") }}
          </h3>
          <p
            class="text-surface-600 dark:text-surface-400 mb-8 leading-relaxed"
          >
            {{ $t("servicesPage.cards.nearshore.desc") }}
          </p>
          <div class="mt-auto pt-6">
            <NuxtLink
              :to="localePath('/contact')"
              class="inline-flex items-center gap-2 font-semibold text-sm text-surface-900 dark:text-surface-0 hover:text-primary-500 dark:hover:text-primary-400 transition-colors w-fit group/link"
            >
              {{ $t("servicesPage.cards.nearshore.link") }}
              <i
                class="pi pi-arrow-right text-xs group-hover/link:translate-x-1 transition-transform"
              ></i>
            </NuxtLink>
          </div>
        </article>

        <!-- Card 3: Legacy (Span 1) -->
        <article
          class="md:col-span-1 bg-surface-0 dark:bg-surface-900 rounded-2xl border border-surface-200 dark:border-surface-800 p-8 hover:border-surface-300 dark:hover:border-surface-700 hover:shadow-xl dark:shadow-none transition-all duration-300 flex flex-col group"
        >
          <div
            class="mb-6 inline-flex items-center justify-center w-12 h-12 rounded-lg border border-surface-100 dark:border-surface-800 bg-surface-50 dark:bg-surface-950 text-surface-700 dark:text-surface-300 group-hover:border-primary-500/20 group-hover:bg-primary-500/10 group-hover:text-primary-500 transition-colors"
          >
            <i class="pi pi-wrench text-xl"></i>
          </div>
          <h3
            class="text-2xl font-bold text-surface-900 dark:text-surface-0 mb-3 tracking-tight"
          >
            {{ $t("servicesPage.cards.legacy.title") }}
          </h3>
          <p
            class="text-surface-600 dark:text-surface-400 mb-8 leading-relaxed"
          >
            {{ $t("servicesPage.cards.legacy.desc") }}
          </p>
          <div class="mt-auto pt-6">
            <NuxtLink
              :to="localePath('/contact')"
              class="inline-flex items-center gap-2 font-semibold text-sm text-surface-900 dark:text-surface-0 hover:text-primary-500 dark:hover:text-primary-400 transition-colors w-fit group/link"
            >
              {{ $t("servicesPage.cards.legacy.link") }}
              <i
                class="pi pi-arrow-right text-xs group-hover/link:translate-x-1 transition-transform"
              ></i>
            </NuxtLink>
          </div>
        </article>

        <!-- Card 4: AI (Span 2) -->
        <article
          class="md:col-span-2 bg-surface-0 dark:bg-surface-900 rounded-2xl border border-surface-200 dark:border-surface-800 p-8 hover:border-surface-300 dark:hover:border-surface-700 hover:shadow-xl dark:shadow-none transition-all duration-300 flex flex-col group relative overflow-hidden"
        >
          <div
            class="absolute inset-0 bg-primary-500/5 dark:bg-primary-500/10 tech-grid opacity-50 pointer-events-none"
          ></div>
          <div class="relative z-10">
            <div
              class="mb-6 inline-flex items-center justify-center w-12 h-12 rounded-lg bg-surface-900 dark:bg-surface-0 text-surface-0 dark:text-surface-900 shadow-lg group-hover:scale-105 transition-transform"
            >
              <i class="pi pi-sparkles text-xl"></i>
            </div>
            <h3
              class="text-2xl font-bold text-surface-900 dark:text-surface-0 mb-3 tracking-tight"
            >
              {{ $t("servicesPage.cards.ai.title") }}
            </h3>
            <p
              class="text-surface-600 dark:text-surface-400 mb-8 max-w-xl leading-relaxed"
            >
              {{ $t("servicesPage.cards.ai.desc") }}
            </p>
            <ul class="space-y-3 mb-8">
              <li class="flex items-center gap-3">
                <i class="pi pi-check-circle text-primary-500"></i>
                <span
                  class="font-mono text-sm text-surface-700 dark:text-surface-300"
                  >{{ $t("servicesPage.cards.ai.feat1") }}</span
                >
              </li>
              <li class="flex items-center gap-3">
                <i class="pi pi-check-circle text-primary-500"></i>
                <span
                  class="font-mono text-sm text-surface-700 dark:text-surface-300"
                  >{{ $t("servicesPage.cards.ai.feat2") }}</span
                >
              </li>
            </ul>
            <div class="mt-auto pt-6">
              <NuxtLink
                :to="localePath('/contact')"
                class="inline-flex items-center gap-2 font-semibold text-sm text-surface-900 dark:text-surface-0 hover:text-primary-500 dark:hover:text-primary-400 transition-colors w-fit group/link"
              >
                {{ $t("servicesPage.cards.ai.link") }}
                <i
                  class="pi pi-arrow-right text-xs group-hover/link:translate-x-1 transition-transform"
                ></i>
              </NuxtLink>
            </div>
          </div>
        </article>
      </div>
    </section>

    <!-- Integrations Carousel -->
    <IntegrationsCarousel class="mb-32" />

    <!-- CTA Section -->
    <section class="max-w-5xl mx-auto px-6 lg:px-8 relative z-10">
      <div
        class="bg-surface-900 dark:bg-surface-950 rounded-2xl p-12 md:p-16 text-center border border-surface-800 shadow-2xl relative overflow-hidden tech-grid"
      >
        <div class="relative z-10 max-w-2xl mx-auto">
          <h2
            class="text-3xl md:text-5xl font-bold text-surface-0 mb-6 tracking-tight leading-tight"
          >
            {{ $t("servicesPage.cta.title") }}
          </h2>
          <p class="text-lg text-surface-300 mb-10 leading-relaxed">
            {{ $t("servicesPage.cta.subtitle") }}
          </p>
          <div class="flex flex-col sm:flex-row justify-center gap-4">
            <Button
              :label="$t('servicesPage.cta.btn1')"
              icon="pi pi-arrow-right"
              iconPos="right"
              @click="$router.push(localePath('/contact'))"
              class="px-8 py-3"
            />
            <Button
              :label="$t('servicesPage.cta.btn2')"
              icon="pi pi-calendar"
              severity="secondary"
              variant="outlined"
              @click="$router.push(localePath('/contact'))"
            />
          </div>
        </div>
      </div>
    </section>
  </main>
</template>
